#Ejemplo de listado, listas de un tipo de cosas
lista = [1,2,3,4,5]
lista2 =[7,8,9,10]
print("A continuación vamos a explicar las difrentes funcionalidades que pueden tener una lista.")
print("-----------------------------------------------------------------------------------------------")
print("1.Añadir al final de una lista.")
print("\t-Para añadir al final de una lista utilizaremos: .append(loquesea)")
print(f'\t-Observa esta lista --> {lista}')
print("\t-A continuación añadiremos el numero 6 usando lista.append(6)")
lista.append(6)
print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")
print("2.Añadir en cualquier posición de una lista.")
print(f'\t-Para añadir un número en una posición que indiquemos usamos: .insert(posición,lo que se añade)')
print(f'\t-Observa esta lista --> {lista}')
print("\t-A continuación añadiremos el numero 0 en la primera posición usando lista.insert(0,0)")
lista.insert(0,0)
print(f'\t-El resultado es --> {lista}')
print(f'\t-En estos casos se puede poner lista.insert(-1,2) y esto colocará sin dar error el número 2 en la posición que corresponda')
##lista.insert(-1,2)
##print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")
print("3.Repetir elementos")
print(f'\t-Al igual que con las cadenas el operador * nos permite repetir una lista una serie de veces')
print(f'\t-Vamos a utilizar listado*3 para que se imprima 3 veces una cadena')
print(f'\t-El resultado es {lista*3}')
print("-----------------------------------------------------------------------------------------------")
print("4.Combinar listas")
print(f'\t-Para combinar listas utilizaremos: .extend(lista)')
print(f'\t-Recordemos que este método machaca la lista original si no queremos que ocurra esto usaremos el operador +')
print(f'\t-Observa lista 1 --> {lista}')
print(f'\t-Observa lista 2 --> {lista2}')
print("\t-A continuación vamos a utilizar lista.extend(lista2) para combinar dos listas.")
lista.extend(lista2)
print(f'\t-El resultado es --> {lista}')
print(f'\t-Importante si en los parámetros de la función no ponemos una lista pueden salir cosas raras mejor no hacerlo')
print("-----------------------------------------------------------------------------------------------")
print("5.Modificar una lista")
print(f'\t-Para modificar una lista utilizaremos: lista[indice]="valorNuevo"')
print(f'\t-Observa esta lista --> {lista}')
print(f'\t-A continuación modificaré el valor de 0 y le pondre -1 para ver la diferencia usado lista[0] = -1')
lista[0]=-1
print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")    
print("6.Modificar un troceado.")
print(f'\t-Para modificar un troceado utilizaremos: lista[0:2] = [12,13]')
print(f'\t-Cabe aclarar que la lista que estemos añadiendo no tiene que tener la misma longitud que la que estamos modificando.')
print(f'\t-Es decir que si de [0:2] son tres dígitos yo puedo sustituirlos por dos o por 1 o por 4')
print(f'\t-Observa esta lista --> {lista}')
print(f'\t-A continuación modificaré los valores desde el índice 0 hasta el 2 por 1 solo número.')
print(f'\t-Para ello utilizaremos lista[0:2] =[300]')
lista[0:2]=[300]
print(f'\t-El resultado es --> {lista}')
