#Ejemplo de listado, listas de un tipo de cosas
lista = [1,2,3,4,5]
lista2 =[7,8,9,10]
lista3 = [9,2,1,4,5]
listaCadena=["Miguel","Pedro","Juan","Pepe"]
print("A continuación vamos a explicar las difrentes funcionalidades que pueden tener una lista.")
print("-----------------------------------------------------------------------------------------------")
print("1.Añadir al final de una lista.")
print("\t-Para añadir al final de una lista utilizaremos: .append(loquesea)")
print(f'\t-Observa esta lista --> {lista}')
print("\t-A continuación añadiremos el numero 6 usando lista.append(6)")
lista.append(6)
print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")
print("2.Añadir en cualquier posición de una lista.")
print(f'\t-Para añadir un número en una posición que indiquemos usamos: .insert(posición,lo que se añade)')
print(f'\t-Observa esta lista --> {lista}')
print("\t-A continuación añadiremos el numero 0 en la primera posición usando lista.insert(0,0)")
lista.insert(0,0)
print(f'\t-El resultado es --> {lista}')
print(f'\t-En estos casos se puede poner lista.insert(-1,2) y esto colocará sin dar error el número 2 en la posición que corresponda')
##lista.insert(-1,2)
##print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")
print("3.Repetir elementos")
print(f'\t-Al igual que con las cadenas el operador * nos permite repetir una lista una serie de veces')
print(f'\t-Vamos a utilizar listado*3 para que se imprima 3 veces una cadena')
print(f'\t-El resultado es {lista*3}')
print("-----------------------------------------------------------------------------------------------")
print("4.Combinar listas")
print(f'\t-Para combinar listas utilizaremos: .extend(lista)')
print(f'\t-Recordemos que este método machaca la lista original si no queremos que ocurra esto usaremos el operador +')
print(f'\t-Observa lista 1 --> {lista}')
print(f'\t-Observa lista 2 --> {lista2}')
print("\t-A continuación vamos a utilizar lista.extend(lista2) para combinar dos listas.")
lista.extend(lista2)
print(f'\t-El resultado es --> {lista}')
print(f'\t-Importante si en los parámetros de la función no ponemos una lista pueden salir cosas raras mejor no hacerlo')
print("-----------------------------------------------------------------------------------------------")
print("5.Modificar una lista")
print(f'\t-Para modificar una lista utilizaremos: lista[indice]="valorNuevo"')
print(f'\t-Observa esta lista --> {lista}')
print(f'\t-A continuación modificaré el valor de 0 y le pondre -1 para ver la diferencia usado lista[0] = -1')
lista[0]=-1
print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")    
print("6.Modificar un troceado.")
print(f'\t-Para modificar un troceado utilizaremos: lista[0:2] = [12,13]')
print(f'\t-Cabe aclarar que la lista que estemos añadiendo no tiene que tener la misma longitud que la que estamos modificando.')
print(f'\t-Es decir que si de [0:2] son tres dígitos yo puedo sustituirlos por dos o por 1 o por 4')
print(f'\t-Observa esta lista --> {lista}')
print(f'\t-A continuación modificaré los valores desde el índice 0 hasta el 2 por 1 solo número.')
print(f'\t-Para ello utilizaremos lista[0:2] =[300]')
lista[0:2]=[300]
print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")
print("7.Borrar elementos")
print(f'\t-Para borrar un elemento de una lista hay dos formas: del lista[indiceAEliminar] o lista.remove(numeroaEliminar)')   
print(f'\t-Observa esta lista --> {lista}')
print(f'A continuación eliminaremos mendiante indice usando del lista[1]')
del lista [1]
print(f'\t-El resultado es --> {lista}')
print(f'A continuación eliminaremos utilizando lista.remove(300) para eliminar el número 300')
lista.remove(300)
print(f'\t-El resultado es --> {lista}')
print(f'\t-Cabe aclarar que si existen valores duplicados el remove solo elimina el primero que encuentre.')
print(f'\t-Además de esas dos existe también la función .pop la cuál extrae el elemento de la lista y nos lo devuelve a la vez que lo elimina de la lista.')
producto = lista.pop(1)
print(f'El número extraído es: {producto}')
print(f'\t-El resultado es --> {lista}')
print(f'\t-También existe la forma de hacerlo mediante rangos haciendo lo siguiente')
print(f'\t-lista[1:4]=[]')
lista[1:4]=[]
print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")
print(f'8.Borrado completo de una lista')
print(f'\t-Hay dos formas utilizando lista.clear() o lista = []')
print(f'\t-Observa esta lista --> {lista}')
##lista.clear() Lo comento para poder seguir trabajando
print(f'\t-El resultado es --> {lista}')
##lista = []
print(f'\t-El resultado es --> {lista}')
print("-----------------------------------------------------------------------------------------------")
print(f'9.Encontrar un elemento')
print(f'Podemos utilizar .index(elemento)')
print(f'\t-Observa esta lista --> {lista}')
print(f'{lista.index(3)}')
print("-----------------------------------------------------------------------------------------------")
print(f'10.Pertenencia a un elemento')
print(f'\t-Para este utilizamos el operador in')
print(f'\t-0 in lista')
print(f'\t-{0 in lista}')
print(f'\t-9 in lista')
print(f'\t-{9 in lista}')
print("-----------------------------------------------------------------------------------------------")
print(f'11.Número de ocurrencias')
print(f'\t-En este utilizaremos .count y nos indica la cantidad de veces que se repite un elemento en la lista')
print(f'\t-En este caso utilizaré este ejemplo lista.count(10)')
print(f'\t-Observa esta lista --> {lista}')
print(f'\t-Resultado:{lista.count(10)}')
print("-----------------------------------------------------------------------------------------------")
print(f'12.Convertir lista a cadena de texto')
print(f'\t-Para convertir una lista en cadena debemos unir sus elementos mediante un separador ya sea "," - " "  o "|"')
print(f'\t-En este caso utilizaré " ".join(lista)')
#print(f'\t-Resultado: {','.join(lista)}')
print(f'\t-En este caso da error ya que solo funciona si tus elementos de la lista son cadenas de texto.')
print("-----------------------------------------------------------------------------------------------")
print(f'13.Ordenar una lista')
print(f'\t-Para hacer esto hay dos formas 1.sorted(lista) o 2. sorted(lista,reverse=True)')
print(f'\t-Observa esta lista --> {lista3}')
print(f'\t-Resultado normal: {sorted(lista3)}')
print(f'\t-Resultado invertido: {sorted(lista3,reverse=True)}')
#Invertir una lista
#lista.reverse Modifica la lista original
#list(reversed(lista)) No modifica la original
print("-----------------------------------------------------------------------------------------------")
print(f'14.Longitud de una lista')
print(f'\t-Para ello utilizaremos len(lista)')
print(f'\t-{len(lista)}')
print("-----------------------------------------------------------------------------------------------")
print(f'15.Iterar sobre una lista')
for num in lista:
    print(f'Num: {num}')

print("-----------------------------------------------------------------------------------------------")
print(f'16.Iterar usando enumeración')
for i, numero in enumerate(lista):
    print(i,numero)
print("-----------------------------------------------------------------------------------------------")
print(f'17.Iterar sobre múltiples listas.')
print(f'\t-Se pueden iterar varias listas utilizando .zip(lista1,lista2)')
for numero1,cadena in zip(lista,listaCadena):
    print(numero1,cadena)

print(f'\t- En el caso de que no tengan la misma longitud solo se repetirá hasta que acabe la más pequeña.')
print(f'\t-Si queremos extraer la una lista de una mezcla de estas dos utilizaremos lo siguiente.')
print(f'\t-{list(zip(lista,listaCadena))}')
print("-----------------------------------------------------------------------------------------------")
print(f'18.Comparar listas')
print(f'{lista>lista2}')
print(f'\t-Esta función va comparando número a número')
print("-----------------------------------------------------------------------------------------------")
print(f'19.Cuidado con las copias.')
print(f'-En este caso debemos tener cuidado ya que si modificamos una lista copiada podemos modificar la original.')
print(f'\t-Lista antes de modificar la copia')
print(f'\t-Lista original: {lista}')
copia_lista1= lista
copia_lista1[0]=-200
print(f'\t-Lista después de modificar la copia')
print(f'\t-Lista original: {lista}')
print(f'\t-Copia: {copia_lista1}')
print(f'\t-Existen dos posibles soluciones 1.copia_lista1 = lista.copy() 2.copia_lista1 = lista[:]')
print(f'Ejemplo .copy con la lista1')
copia_lista1 = lista.copy()
copia_lista1[0] = 50
print(f'\t-Lista: {lista}')
print(f'\t-Copia lista: {copia_lista1}')
print(f'Ejemplo [:] con la lista2')
copia_lista2 = lista2[:]
copia_lista2[0] =12321322
print(f'\t-Lista: {lista2}')
print(f'\t-Copia lista: {copia_lista2}')
print("-----------------------------------------------------------------------------------------------")
print(f'20.Veracidad múltiple')
print(f'\t-En este caso Python nos permite dos funciones: ')
print(f'\t-1.all() para comprobar si se cumplen todas.')
print(f'\t-2.any() para comprobar si se cumplen alguna.')
print(f'\t-Estas listas trabajan sobre iterables.')
print(f'\t-Para comprobar si la longitud de la lista es mayor que 2 y contiene al menos un 10')
print(f'\t-Usaremos: longitud = len(lista1)>2, numero = lista.count(10)>=1')
print(f'\t-Y después lo igualaremos  a una variables.')
longitud = len(lista)>2
numero = lista.count(10)
iscierto = all([longitud,numero])

if iscierto:
    print("Se cumple")
else:
    print("No se cumple")

print(f'\t-Ahora utilizaremos una verdadera para ver si se cumple con any')
longitud = len(lista)>5
numero = lista.count(10)

iscierto = any([longitud,numero])

if iscierto:
    print("Se cumple")
else:
    print("No se cumple")
